# Generated by CMake 2.8.12.2

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget KommonCore KommonRoot KommonGsl KommonVtk KGeoBagMath KGeoBagMathLinearAlgebra KGeoBagMathSpaceTree KGeoBagCore KGeoBagShapes KGeoBagMesh KGeoBagAxialMesh KGeoBagDiscreteRotationalMesh KGeoBagAppearance KGeoBagMetrics KGeoBagRandom KGeoBagIntersection KGeoBagDeformation KGeoBagBasicVisualization KGeoBagVtkVisualization KGeoBagROOTVisualization KGeoBagBindings KGeoBag RandomExtensionTester MetricsExtensionTester GeometryViewer MeshViewer AxialMeshViewer PointTester NormalTester DistanceTester OutsideTester RandomPointTester GeometryViewerROOT KEMCore KEMHashGenerator KEMStructuredASCII KEMIO KEMFileManipulation KEMMath KFMMathUtilities KVectorMath KEMSurfaces KEMElectrostaticBoundaryIntegrals KEMElectromagnets KEMIntegratingFieldSolver KEMZHGenerator KEMZHSolver KFMCore KFMMath KFMKernel KFMTree KFMElectrostatics KFMInterfaceExtraction KFMInterfaceFieldSolvers KFMUtility KEMVisualization KEMGeoBagPlugin ComputeChargeDensities ComputeSphericalCapacitor TransferEMElement HashEMGeometry InspectEMFile KassiopeiaUtility KassiopeiaMath KassiopeiaObjects KassiopeiaOperators KassiopeiaFields KassiopeiaGeometry KassiopeiaGenerators KassiopeiaTrajectories KassiopeiaNavigators KassiopeiaInteractions KassiopeiaTerminators KassiopeiaModifiers KassiopeiaWriters KassiopeiaReaders KassiopeiaVisualization KassiopeiaSimulation KassiopeiaBindings Kassiopeia TestInteraction TestHydrogenInteraction TestArgonInteraction TestZonalHarmonicsConvergence QuadrupoleTrapAnalysis ROOTFileMerge)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target KommonCore
add_library(KommonCore SHARED IMPORTED)

# Create imported target KommonRoot
add_library(KommonRoot SHARED IMPORTED)

# Create imported target KommonGsl
add_library(KommonGsl SHARED IMPORTED)

# Create imported target KommonVtk
add_library(KommonVtk SHARED IMPORTED)

# Create imported target KGeoBagMath
add_library(KGeoBagMath SHARED IMPORTED)

# Create imported target KGeoBagMathLinearAlgebra
add_library(KGeoBagMathLinearAlgebra SHARED IMPORTED)

# Create imported target KGeoBagMathSpaceTree
add_library(KGeoBagMathSpaceTree SHARED IMPORTED)

# Create imported target KGeoBagCore
add_library(KGeoBagCore SHARED IMPORTED)

# Create imported target KGeoBagShapes
add_library(KGeoBagShapes SHARED IMPORTED)

# Create imported target KGeoBagMesh
add_library(KGeoBagMesh SHARED IMPORTED)

# Create imported target KGeoBagAxialMesh
add_library(KGeoBagAxialMesh SHARED IMPORTED)

# Create imported target KGeoBagDiscreteRotationalMesh
add_library(KGeoBagDiscreteRotationalMesh SHARED IMPORTED)

# Create imported target KGeoBagAppearance
add_library(KGeoBagAppearance SHARED IMPORTED)

# Create imported target KGeoBagMetrics
add_library(KGeoBagMetrics SHARED IMPORTED)

# Create imported target KGeoBagRandom
add_library(KGeoBagRandom SHARED IMPORTED)

# Create imported target KGeoBagIntersection
add_library(KGeoBagIntersection SHARED IMPORTED)

# Create imported target KGeoBagDeformation
add_library(KGeoBagDeformation SHARED IMPORTED)

# Create imported target KGeoBagBasicVisualization
add_library(KGeoBagBasicVisualization SHARED IMPORTED)

# Create imported target KGeoBagVtkVisualization
add_library(KGeoBagVtkVisualization SHARED IMPORTED)

# Create imported target KGeoBagROOTVisualization
add_library(KGeoBagROOTVisualization SHARED IMPORTED)

# Create imported target KGeoBagBindings
add_library(KGeoBagBindings SHARED IMPORTED)

# Create imported target KGeoBag
add_executable(KGeoBag IMPORTED)

# Create imported target RandomExtensionTester
add_executable(RandomExtensionTester IMPORTED)

# Create imported target MetricsExtensionTester
add_executable(MetricsExtensionTester IMPORTED)

# Create imported target GeometryViewer
add_executable(GeometryViewer IMPORTED)

# Create imported target MeshViewer
add_executable(MeshViewer IMPORTED)

# Create imported target AxialMeshViewer
add_executable(AxialMeshViewer IMPORTED)

# Create imported target PointTester
add_executable(PointTester IMPORTED)

# Create imported target NormalTester
add_executable(NormalTester IMPORTED)

# Create imported target DistanceTester
add_executable(DistanceTester IMPORTED)

# Create imported target OutsideTester
add_executable(OutsideTester IMPORTED)

# Create imported target RandomPointTester
add_executable(RandomPointTester IMPORTED)

# Create imported target GeometryViewerROOT
add_executable(GeometryViewerROOT IMPORTED)

# Create imported target KEMCore
add_library(KEMCore SHARED IMPORTED)

# Create imported target KEMHashGenerator
add_library(KEMHashGenerator SHARED IMPORTED)

# Create imported target KEMStructuredASCII
add_library(KEMStructuredASCII SHARED IMPORTED)

# Create imported target KEMIO
add_library(KEMIO SHARED IMPORTED)

# Create imported target KEMFileManipulation
add_library(KEMFileManipulation SHARED IMPORTED)

# Create imported target KEMMath
add_library(KEMMath SHARED IMPORTED)

# Create imported target KFMMathUtilities
add_library(KFMMathUtilities SHARED IMPORTED)

# Create imported target KVectorMath
add_library(KVectorMath SHARED IMPORTED)

# Create imported target KEMSurfaces
add_library(KEMSurfaces SHARED IMPORTED)

# Create imported target KEMElectrostaticBoundaryIntegrals
add_library(KEMElectrostaticBoundaryIntegrals SHARED IMPORTED)

# Create imported target KEMElectromagnets
add_library(KEMElectromagnets SHARED IMPORTED)

# Create imported target KEMIntegratingFieldSolver
add_library(KEMIntegratingFieldSolver SHARED IMPORTED)

# Create imported target KEMZHGenerator
add_library(KEMZHGenerator SHARED IMPORTED)

# Create imported target KEMZHSolver
add_library(KEMZHSolver SHARED IMPORTED)

# Create imported target KFMCore
add_library(KFMCore SHARED IMPORTED)

# Create imported target KFMMath
add_library(KFMMath SHARED IMPORTED)

# Create imported target KFMKernel
add_library(KFMKernel SHARED IMPORTED)

# Create imported target KFMTree
add_library(KFMTree SHARED IMPORTED)

# Create imported target KFMElectrostatics
add_library(KFMElectrostatics SHARED IMPORTED)

# Create imported target KFMInterfaceExtraction
add_library(KFMInterfaceExtraction SHARED IMPORTED)

# Create imported target KFMInterfaceFieldSolvers
add_library(KFMInterfaceFieldSolvers SHARED IMPORTED)

# Create imported target KFMUtility
add_library(KFMUtility SHARED IMPORTED)

# Create imported target KEMVisualization
add_library(KEMVisualization SHARED IMPORTED)

# Create imported target KEMGeoBagPlugin
add_library(KEMGeoBagPlugin SHARED IMPORTED)

# Create imported target ComputeChargeDensities
add_executable(ComputeChargeDensities IMPORTED)

# Create imported target ComputeSphericalCapacitor
add_executable(ComputeSphericalCapacitor IMPORTED)

# Create imported target TransferEMElement
add_executable(TransferEMElement IMPORTED)

# Create imported target HashEMGeometry
add_executable(HashEMGeometry IMPORTED)

# Create imported target InspectEMFile
add_executable(InspectEMFile IMPORTED)

# Create imported target KassiopeiaUtility
add_library(KassiopeiaUtility SHARED IMPORTED)

# Create imported target KassiopeiaMath
add_library(KassiopeiaMath SHARED IMPORTED)

# Create imported target KassiopeiaObjects
add_library(KassiopeiaObjects SHARED IMPORTED)

# Create imported target KassiopeiaOperators
add_library(KassiopeiaOperators SHARED IMPORTED)

# Create imported target KassiopeiaFields
add_library(KassiopeiaFields SHARED IMPORTED)

# Create imported target KassiopeiaGeometry
add_library(KassiopeiaGeometry SHARED IMPORTED)

# Create imported target KassiopeiaGenerators
add_library(KassiopeiaGenerators SHARED IMPORTED)

# Create imported target KassiopeiaTrajectories
add_library(KassiopeiaTrajectories SHARED IMPORTED)

# Create imported target KassiopeiaNavigators
add_library(KassiopeiaNavigators SHARED IMPORTED)

# Create imported target KassiopeiaInteractions
add_library(KassiopeiaInteractions SHARED IMPORTED)

# Create imported target KassiopeiaTerminators
add_library(KassiopeiaTerminators SHARED IMPORTED)

# Create imported target KassiopeiaModifiers
add_library(KassiopeiaModifiers SHARED IMPORTED)

# Create imported target KassiopeiaWriters
add_library(KassiopeiaWriters SHARED IMPORTED)

# Create imported target KassiopeiaReaders
add_library(KassiopeiaReaders SHARED IMPORTED)

# Create imported target KassiopeiaVisualization
add_library(KassiopeiaVisualization SHARED IMPORTED)

# Create imported target KassiopeiaSimulation
add_library(KassiopeiaSimulation SHARED IMPORTED)

# Create imported target KassiopeiaBindings
add_library(KassiopeiaBindings SHARED IMPORTED)

# Create imported target Kassiopeia
add_executable(Kassiopeia IMPORTED)

# Create imported target TestInteraction
add_executable(TestInteraction IMPORTED)

# Create imported target TestHydrogenInteraction
add_executable(TestHydrogenInteraction IMPORTED)

# Create imported target TestArgonInteraction
add_executable(TestArgonInteraction IMPORTED)

# Create imported target TestZonalHarmonicsConvergence
add_executable(TestZonalHarmonicsConvergence IMPORTED)

# Create imported target QuadrupoleTrapAnalysis
add_executable(QuadrupoleTrapAnalysis IMPORTED)

# Create imported target ROOTFileMerge
add_executable(ROOTFileMerge IMPORTED)

# Load information for each installed configuration.
get_filename_component(_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
file(GLOB CONFIG_FILES "${_DIR}/KasperTargets-*.cmake")
foreach(f ${CONFIG_FILES})
  include(${f})
endforeach()

# Loop over all imported files and verify that they actually exist
foreach(target ${_IMPORT_CHECK_TARGETS} )
  foreach(file ${_IMPORT_CHECK_FILES_FOR_${target}} )
    if(NOT EXISTS "${file}" )
      message(FATAL_ERROR "The imported target \"${target}\" references the file
   \"${file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
")
    endif()
  endforeach()
  unset(_IMPORT_CHECK_FILES_FOR_${target})
endforeach()
unset(_IMPORT_CHECK_TARGETS)

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
